# -*- coding: utf-8 -*-
"""Anosha-PythonBasics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_WJBDaRJe1ePO6VEV_7CcWjnEWPVuVin
"""

#Write a program that prints your name and includes both single-line and multi-line comments explaining what each part of your code does.

name = "Anosha"
# name variable store string "Anosha"
"""print is a built-in method
this method is used to print any string, number etc"""
print(name)

"""**Exercise 2: Error Identification**"""

#print("Welcome to Python!"
#Above is a Syntax error
print("Welcome to Python!")

# result = 10 / 0
#Above is a Runtime error
result = 10/1
print(result)

# my_list = [1, 2, 3
#Above is a Syntax error
my_list = [1, 2, 3]
print(my_list)

# print(my_list[3])
#If my_list contain [1, 2, 3] it can be index error and removed if we call 0 to n-1 index number
print(my_list[2])

"""**Exercise 3: Variable Assignment**"""

"""
Create a program that:
Assign your name (string), age (integer), height (float), and whether you are a student (boolean) to variables.
Prints each variable with an appropriate message."""

name = "Anosha"
age = 21
height = 5.4
student = True

print('Name : ', name)
print('Age : ', age)
print('Height : ', height)
print('Student : ', student)

"""**Exercise 4: Descriptive Variable Names**"""

''' a = 5
b = 10
c = a * b
print(c) '''
length = 5
width = 10
area = 5*10
print("Area of square : ", area)

"""**Exercise 5: Numeric Types and Operations**"""

#Add two integers
print('Addition', 2+3)
#Subtract a float from an integer
print('Substraction', 12.55-3.65)
#Multiply a float by a complex number
print("Multiplication of Complex number ", (2+5j)*(10+6j))

#Divide an integer by zero (observe and write down the error)
print(6/0) # It is a RunTime Error

#Error will be removed if we never divide by 0
print(6/1)

"""**Exercise 6: Built-in Functions**"""

"""Takes a list of numbers as input from the user.
Uses the abs(), max(), and min() functions to find the absolute values, maximum, and minimum of the numbers.
Prints the results with appropriate messages."""
list = []
user_input = int(input("Enter number one : "))
list.append(user_input)
user_input = int(input("Enter number two : "))
list.append(user_input)
user_input = int(input("Enter number three : "))
list.append(user_input)
#[1000, 2000, -1]
print("Max = ", max(list))
print("Min = ", min(list))
print("Abs = ", abs(user_input))

"""**Exercise 7: Arithmetic Operation**"""

"""Create a simple calculator program that:
Prompts the user to enter two numbers.
Asks the user to select an operation: addition, subtraction, multiplication, or division.
Performs the selected operation and prints the result. Handle division by zero gracefully."""
input1 = int(input("Enter number one : "))
input2 = int(input("Enter number two : "))
print("Press 1 for Addition")
print("Press 2 for Subtraction")
print("Press 3 for Multiplication")
print("Press 4 for Division")
user_choice = int(input())
if(user_choice == 1):
 print("Addition : ", (input1+input2))
if(user_choice == 2):
 print("Subtraction : ", (input1-input2))
if(user_choice == 3):
 print("Multiplication : ", (input1*input2))
if(user_choice == 4):
 print("Division : ", (input1/input2))